### ISSUE TITLE
Consistently use British english in Array

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/development#208]
I stumble across `array.hpp` having code such as:

```c++
explicit Array(const SizeType n, Uninitialised) : _size(n), _ptr(uninitialized_new(n)) { }
/*! \brief Constructs an Array of size \a n with elements initialised to \a x. */
Array(const SizeType n, const ValueType& x) : _size(n), _ptr(uninitialized_new(n)) { this->_uninitialized_fill(x); }
```

where we clearly haven't made our mind about using initialized rather than initialised. However, it seems that array.hpp is the only file that has this specific inconsistency.

Shall we "fix" this into British @pietercollins?

**Comment by pietercollins** [comment]
I tend to mix the two, with a slight preference for American English for names with parallels in the standard library, for technical computer science terms, and for -ize over -ise. So `Uninitialized` and `InitializerList`, since we have `std::initializer_list`. I have a slight preference for British English in documentation, for non-technical terms, and for -our over -or. Hence `Colour` not `Color`.

**Comment by pietercollins** [comment]
I have also noticed `minimise` not `minimize`, and `initialise` in the Graphics module. However, `minimize` is not a name in the C++ standard library, so we can keep it.

**Comment by lgeretti** [comment]
Shall we move to American English for consistency? Is that ok with you?
